name: Docker Stack Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@v1.0.3
      env:
        GIT_PROJECT: "vps-contabo-github-runner"
        DOCKER_STACK: "github-runner"
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        GH_REPO: ${{ secrets.GH_REPO }}
      with:
        host: ${{ secrets.CONTABO_SSH_HOST }}
        username: ${{ secrets.CONTABO_SSH_USER }}
        key: ${{ secrets.CONTABO_SSH_PRIVATE_KEY }}
        port: 22
        envs: GIT_PROJECT,DOCKER_STACK,GH_ACCESS_TOKEN,GH_REPO
        script_stop: true # stop on first failure
        script: |
          echo "removing old git repo clone"
          rm -rf $GIT_PROJECT
          
          echo "cloning git repo"
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone --depth 1 git@github.com:christiangroth/$GIT_PROJECT.git $GIT_PROJECT
          cd $GIT_PROJECT
          
          echo "deploying docker stack"
          GH_ACCESS_TOKEN=$GH_ACCESS_TOKEN GH_REPO=$GH_REPO \
            docker stack rm $DOCKER_STACK
          sleep 5
          
          echo
          echo "----- ----- -----"
          echo "----- ----- -----"
          echo "----- ----- -----"
          echo
          
          docker stack ls
          echo
          docker stack services $DOCKER_STACK
          echo
          docker stack ps $DOCKER_STACK
          
          echo "removing git repo clone"
          cd ..
          rm -rf $GIT_PROJECT
